version: 2

sources:
    - name: fergus_jaffle_shop
      description: This is a replica of the Postgres database used by our app
      database: TIL_PORTFOLIO_PROJECTS
      schema: jaffle_shop
      tables:
          - name: customers
            description: One record per customer.
            columns:
              - name: id
                description: primary key for customers data
          - name: orders
            description: One record per order. Includes cancelled and deleted orders.
            loaded_at_field: _etl_loaded_at
            freshness: 
              warn_after: {count: 12, period: hour}
              error_after: {count: 24, period: hour}
            